"""Column role add to table User

Revision ID: 4309720a0386
Revises: f4f382b5eac4
Create Date: 2026-05-27 01:42:26.172804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4309720a0386'
down_revision: Union[str, Sequence[str], None] = 'f4f382b5eac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = sa.Enum(
    'admin',
    'client',
    'vendedor',
    name='role_type'
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'users',
        sa.Column(
            'role',
            role_enum,
            nullable=False,
            server_default='client'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
